<a href="https://colab.research.google.com/github/gurrapurajkumar99/2303A51782-application-of-data-mining/blob/main/Assignment2_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import pandas as pd

In [7]:
df=pd.read_csv("student-dataset.csv")

In [8]:
df.head(

)

,id,name,nationality,city,latitude,longitude,gender,age,english.grade,math.grade,sciences.grade,language.grade,portfolio.rating,coverletter.rating,refletter.rating
0,0,Kiana Lor,China,Suzhou,31.31,120.62,F,22,3.5,3.7,3.1,1.0,4,4.0,4
1,1,Joshua Lonaker,United States of America,Santa Clarita,34.39,-118.54,M,22,2.9,3.2,3.6,5.0,5,4.0,5
2,2,Dakota Blanco,United States of America,Oakland,37.80,-122.27,F,22,3.9,3.8,3.2,5.0,3,3.0,4
3,3,Natasha Yarusso,United States of America,Castro Valley,37.69,-122.09,F,20,3.3,2.8,NaN,5.0,5,2.0,4
4,4,Brooke Cazares,Brazil,São José dos Campos,-23.18,-45.88,F,21,3.7,2.6,3.4,1.0,4,4.0,5

In [10]:
df.isnull().sum()

id                    0
name                  0
nationality           0
city                  0
latitude              0
longitude             0
gender                0
age                   0
english.grade         0
math.grade            0
sciences.grade        9
language.grade        0
portfolio.rating      0
coverletter.rating    0
refletter.rating      0
dtype: int64

In [14]:
df["sciences.grade"].fillna(df["sciences.grade"].median(),inplace=True)

In [19]:
from sklearn.preprocessing import MinMaxScaler

In [20]:
SCA=MinMaxScaler()

In [22]:
df[["english.grade","math.grade","sciences.grade","language.grade"]]=SCA.fit_transform(df[["english.grade","math.grade","sciences.grade","language.grade"]])

In [23]:
df.head()

,id,name,nationality,city,latitude,longitude,gender,age,english.grade,math.grade,sciences.grade,language.grade,portfolio.rating,coverletter.rating,refletter.rating
0,0,Kiana Lor,China,Suzhou,31.31,120.62,F,22,0.80,0.842105,0.653846,0.0,4,4.0,4
1,1,Joshua Lonaker,United States of America,Santa Clarita,34.39,-118.54,M,22,0.56,0.578947,0.846154,1.0,5,4.0,5
2,2,Dakota Blanco,United States of America,Oakland,37.80,-122.27,F,22,0.96,0.894737,0.692308,1.0,3,3.0,4
3,3,Natasha Yarusso,United States of America,Castro Valley,37.69,-122.09,F,20,0.72,0.368421,0.846154,1.0,5,2.0,4
4,4,Brooke Cazares,Brazil,São José dos Campos,-23.18,-45.88,F,21,0.88,0.263158,0.769231,0.0,4,4.0,5